/*
 * JS for Twilio_SMS generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'b91e4327-0ee8-4ab0-b922-c92eb8bb9fcc';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Twilio_SMS",
    "location": "Twilio_SMS.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}];

Twilio_SMS_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel4': 'Twilio_SMS_mobilelabel4',
        'mobilelabel5': 'Twilio_SMS_mobilelabel5',
        'mobilelabel1': 'Twilio_SMS_mobilelabel1',
        'message': 'Twilio_SMS_message',
        'mobilebutton1': 'Twilio_SMS_mobilebutton1',
        'errorMessage': 'Twilio_SMS_errorMessage',
        'sentMessage': 'Twilio_SMS_sentMessage',
        'to': 'Twilio_SMS_to',
        'from': 'Twilio_SMS_from'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'Twilio_SMS';

    /*
     * Nonvisual components
     */
    var datasources = [];

    smsService = new Apperyio.DataSource(Twilio_SMSService, {
        'onBeforeSend': function(jqXHR) {

        },
        'onComplete': function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("Twilio_SMS");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['message'],
            'ID': 'errorMessage',
            'ATTR': 'visible',
            'TRANSFORMATION': function(value, element) {
                return !!value;
            }
        }, {
            'PATH': ['status'],
            'ID': 'sentMessage',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                if (value == 'queued') return 'Message sent';
                else return '';
            }
        }, {
            'PATH': ['message'],
            'ID': 'errorMessage',
            'ATTR': '@'
        }, {
            'PATH': ['status'],
            'ID': 'sentMessage',
            'ATTR': 'visible',
            'TRANSFORMATION': function(value, element) {
                element.show();
                return true;
            }
        }],
        'requestMapping': [{
            'PATH': ['From'],
            'TYPE': 'STRING',
            'ID': 'from',
            'ATTR': 'value'
        }, {
            'PATH': ['To'],
            'TYPE': 'STRING',
            'ID': 'to',
            'ATTR': 'value'
        }, {
            'PATH': ['Body'],
            'TYPE': 'STRING',
            'ID': 'message',
            'ATTR': 'value'
        }, {
            'PATH': ['Authorization'],
            'TYPE': 'STRING',
            'HEADER': true,
            'TRANSFORMATION': function(value) {
                var auth = Twilio_Settings.AccountSid + ':' + Twilio_Settings.AuthToken;
                return "Basic " + btoa(auth);
            }
        }, {
            'PATH': ['appery-proxy-url'],
            'HEADER': true,
            'ATTR': 'https://api.twilio.com/2010-04-01/Accounts/{AccountSid}/SMS/Messages.json'
        }, {
            'PATH': ['appery-transformation'],
            'HEADER': true,
            'ATTR': 'checkTunnel'
        }, {
            'PATH': ['appery-key'],
            'HEADER': true,
            'ATTR': '1411261519611'
        }, {
            'PATH': ['appery-rest'],
            'HEADER': true,
            'ATTR': '2615440'
        }]
    });

    datasources.push(smsService);

    /*
     * Events and handlers
     */

    // Before Show
    var Twilio_SMS_beforeshow = function() {
            Apperyio.CurrentScreen = "Twilio_SMS";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var Twilio_SMS_onLoad = function() {
            Twilio_SMS_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            Twilio_SMS_deviceEvents();
            Twilio_SMS_windowEvents();
            Twilio_SMS_elementsEvents();
        };

    // screen window events
    var Twilio_SMS_windowEvents = function() {

            $('#Twilio_SMS').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var Twilio_SMS_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var Twilio_SMS_elementsExtraJS = function() {
            // screen (Twilio_SMS) extra code

        };

    // screen elements handler
    var Twilio_SMS_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#Twilio_SMS_mobilecontainer1 [name="mobilebutton1"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Appery('errorMessage').hide();
                        Appery('sentMessage').hide();
                        try {
                            smsService.execute({})
                        } catch (ex) {
                            console.log(ex.name + '  ' + ex.message);
                            hideSpinner();
                        };

                    }
                },
            }, '#Twilio_SMS_mobilecontainer1 [name="mobilebutton1"]');

        };

    $(document).off("pagebeforeshow", "#Twilio_SMS").on("pagebeforeshow", "#Twilio_SMS", function(event, ui) {
        Twilio_SMS_beforeshow();
    });

    if (runBeforeShow) {
        Twilio_SMS_beforeshow();
    } else {
        Twilio_SMS_onLoad();
    }
};

$(document).off("pagecreate", "#Twilio_SMS").on("pagecreate", "#Twilio_SMS", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Twilio_SMS_js();
});