/*
 * JS for startScreen generated by Appery.io
 *
 */

Apperyio.getProjectGUID = function() {
    return 'bfbca7e0-f27b-4373-a843-cdc129c4e93c';
}

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "agAccessoriesPage",
    "location": "agAccessoriesPage.html"
}, {
    "name": "barbieSellToyPopup",
    "location": "barbieSellToyPopup.html"
}, {
    "name": "agBookPopup",
    "location": "agBookPopup.html"
}, {
    "name": "barbieBuyOnePopup",
    "location": "barbieBuyOnePopup.html"
}, {
    "name": "barbieAccessoriesPopup",
    "location": "barbieAccessoriesPopup.html"
}, {
    "name": "agBuyDollPopup",
    "location": "agBuyDollPopup.html"
}, {
    "name": "agStoryPopup",
    "location": "agStoryPopup.html"
}, {
    "name": "agPricingPage",
    "location": "agPricingPage.html"
}, {
    "name": "barbiePricingPopup",
    "location": "barbiePricingPopup.html"
}, {
    "name": "barbieStoryPopup",
    "location": "barbieStoryPopup.html"
}, {
    "name": "ogAccessoriesPopup",
    "location": "ogAccessoriesPopup.html"
}, {
    "name": "dollAuctionRoom",
    "location": "dollAuctionRoom.html"
}, {
    "name": "cammera",
    "location": "cammera.html"
}, {
    "name": "agPage",
    "location": "agPage.html"
}, {
    "name": "barbiePage",
    "location": "barbiePage.html"
}, {
    "name": "dollPopup",
    "location": "dollPopup.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "barbieBookPopup",
    "location": "barbieBookPopup.html"
}, {
    "name": "ogPage",
    "location": "ogPage.html"
}, {
    "name": "ogPricingPopup",
    "location": "ogPricingPopup.html"
}, {
    "name": "ogStoryPopup",
    "location": "ogStoryPopup.html"
}, {
    "name": "ogBookPopup",
    "location": "ogBookPopup.html"
}];

startScreen_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'dollsBtn': 'startScreen_dollsBtn',
        'stuffedAnimalsBtn': 'startScreen_stuffedAnimalsBtn',
        'gamesBtn': 'startScreen_gamesBtn',
        'petBtn': 'startScreen_petBtn',
        'carsBtn': 'startScreen_carsBtn',
        'ridingToysBtn': 'startScreen_ridingToysBtn'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Apperyio.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Apperyio.CurrentScreen = 'startScreen';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    startScreen_beforeshow = function() {
        Apperyio.CurrentScreen = "startScreen";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_3671_onLoad = startScreen_onLoad = function() {
        screen_3671_elementsExtraJS();

        // TODO fire device events only if necessary (with JS logic)
        startScreen_deviceEvents();
        startScreen_windowEvents();
        screen_3671_elementsEvents();
    }

    // screen window events
    screen_3671_windowEvents = startScreen_windowEvents = function() {

        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    }

    // device events
    startScreen_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_3671_elementsExtraJS = startScreen_elementsExtraJS = function() {
        // screen (startScreen) extra code

    }

    // screen elements handler
    screen_3671_elementsEvents = startScreen_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#startScreen_mobilecontainer1 [name="dollsBtn"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('dollPopup', {
                        transition: 'pop'
                    });

                }
            },
        });

    }

    $("#startScreen").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        startScreen_beforeshow();
    });

    if (runBeforeShow) {
        startScreen_beforeshow();
    } else {
        startScreen_onLoad();
    }

}

$("#startScreen").die("pageinit").live("pageinit", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});