/*
 * JS for aboutPage generated by Appery.io
 *
 */

Apperyio.getProjectGUID = function() {
    return 'fefedff7-2195-4035-b707-62edda0f92ae';
}

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "aboutPage",
    "location": "aboutPage.html"
}, {
    "name": "payedDollPage",
    "location": "payedDollPage.html"
}, {
    "name": "foodDetailPage",
    "location": "foodDetailPage.html"
}, {
    "name": "MenuPage",
    "location": "MenuPage.html"
}, {
    "name": "OrderTracking",
    "location": "OrderTracking.html"
}];

aboutPage_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'aboutPage_mobilelabel_2',
        'spacer_4': 'aboutPage_spacer_4',
        'mobileimage_1': 'aboutPage_mobileimage_1'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Apperyio.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Apperyio.CurrentScreen = 'aboutPage';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    aboutPage_beforeshow = function() {
        Apperyio.CurrentScreen = "aboutPage";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_B933_onLoad = aboutPage_onLoad = function() {
        screen_B933_elementsExtraJS();
        Appery('mobileimage_1').css('margin', 'auto');
        Appery('mobileimage_1').css('display', 'block');

        // TODO fire device events only if necessary (with JS logic)
        aboutPage_deviceEvents();
        aboutPage_windowEvents();
        screen_B933_elementsEvents();
    }

    // screen window events
    screen_B933_windowEvents = aboutPage_windowEvents = function() {

        $('#aboutPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    }

    // device events
    aboutPage_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_B933_elementsExtraJS = aboutPage_elementsExtraJS = function() {
        // screen (aboutPage) extra code

    }

    // screen elements handler
    screen_B933_elementsEvents = aboutPage_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#aboutPage_mobilecontainer1 [name="mobileimage_1"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    window.top.location = 'https://play.google.com/store/apps/details?id=com.digitalartassets.santastoydrop&hl=en';

                }
            },
        });

    }

    $("#aboutPage").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        aboutPage_beforeshow();
    });

    if (runBeforeShow) {
        aboutPage_beforeshow();
    } else {
        aboutPage_onLoad();
    }

}

$("#aboutPage").die("pageinit").live("pageinit", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    aboutPage_js();
});