/*
 * JS for payedDollPage generated by Appery.io
 *
 */

Apperyio.getProjectGUID = function() {
    return 'fefedff7-2195-4035-b707-62edda0f92ae';
}

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "aboutPage",
    "location": "aboutPage.html"
}, {
    "name": "payedDollPage",
    "location": "payedDollPage.html"
}, {
    "name": "foodDetailPage",
    "location": "foodDetailPage.html"
}, {
    "name": "MenuPage",
    "location": "MenuPage.html"
}, {
    "name": "OrderTracking",
    "location": "OrderTracking.html"
}];

payedDollPage_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileimage_2': 'payedDollPage_mobileimage_2',
        'mobilelabel_3': 'payedDollPage_mobilelabel_3',
        'mobilebutton_4': 'payedDollPage_mobilebutton_4',
        'mobilebutton_5': 'payedDollPage_mobilebutton_5'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Apperyio.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Apperyio.CurrentScreen = 'payedDollPage';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    payedDollPage_beforeshow = function() {
        Apperyio.CurrentScreen = "payedDollPage";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_ECD5_onLoad = payedDollPage_onLoad = function() {
        screen_ECD5_elementsExtraJS();

        // TODO fire device events only if necessary (with JS logic)
        payedDollPage_deviceEvents();
        payedDollPage_windowEvents();
        screen_ECD5_elementsEvents();
    }

    // screen window events
    screen_ECD5_windowEvents = payedDollPage_windowEvents = function() {

        $('#payedDollPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    }

    // device events
    payedDollPage_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_ECD5_elementsExtraJS = payedDollPage_elementsExtraJS = function() {
        // screen (payedDollPage) extra code

    }

    // screen elements handler
    screen_ECD5_elementsEvents = payedDollPage_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#payedDollPage_mobilecontainer1 [name="mobilebutton_5"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('MenuPage', {
                        reverse: false
                    });

                }
            },
        });

    }

    $("#payedDollPage").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        payedDollPage_beforeshow();
    });

    if (runBeforeShow) {
        payedDollPage_beforeshow();
    } else {
        payedDollPage_onLoad();
    }

}

$("#payedDollPage").die("pageinit").live("pageinit", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    payedDollPage_js();
});